---
title: Matthew Bischoff
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: 
    description: ''
    format: post
    color: 
    link: 
permalink: "/:title/"
url: https://matthewbischoff.com
paginate: 5
baseurl: 
author:
  name: Matthew Bischoff
  url: https://twitter.com/mb
  email: mb@matthewbischoff.com
  twitter: mb
logo: "/uploads/matthew.jpeg"
version: 2
license:
  text: Some rights reserved
  url: http://creativecommons.org/licenses/by-sa/4.0/
plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-feed
- jekyll-redirect-from
twitter:
  username: mb
facebook:
  publisher: https://www.facebook.com/matthewbischoff
  admins: https://www.facebook.com/matthewbischoff
google_site_verification: XK_j6lkDAd8qOhIn4-2eS2BIJuQyRp4D_gxjpR65wUM
sass:
  sass_dir: _sass
  style: compressed
repository: mattbischoff/matthewbischoff.com
include:
- _category
text_content:
  header_title: Hi, I’m Matthew Bischoff
  subtitle: I write about technology & culture. I’ve made apps at NYTimes, Tumblr,
    and now run my own studio, Lickability. I’m glad you’re here.
  short_subtitle: I write about technology & culture. I’ve made apps at NYTimes, Tumblr,
    and now run my own studio, Lickability. I’m glad you’re here.
